[nav]
About = "/about"
Projects = "/projects"
Blog = "/posts"
More = "/more-links"

[more]
Notes = "/notes"
Likes = "/likes"
Feeds = "/feeds"

[contact]
Email = "pranav [at] karawale.in"
Mastodon = "@retronav@fosstodon.org"
IRC = "pranav@tilde.chat / retronav@libera.chat"
Matrix = "@pranav:envs.net"