[nav]
Home = "/"
About = "/about"
Projects = "/projects"
Feeds = "/feeds"
Blog = "/posts"
Notes = "/notes"

[contact]
Email = "my first name [at] this domain"
Mastodon = "@retronav@fosstodon.org"
IRC = "pranav@tilde.chat / retronav@libera.chat"
Matrix = "@pranav:envs.net"