title = "Pranav Karawale"
description = "Pranav Karawale's various things in writing."
webmention = "https://webmention.io/karawale.in/webmention"
pingback = "https://webmention.io/karawale.in/xmlrpc"
author = "Pranav Karawale"

# Based on https://www.aleksandrhovhannisyan.com/blog/configuring-web-fonts-in-11ty-with-global-data/
preloads = [
    {as = "font", type = "font/woff2", href = "/roboto-slab-latin-variable-wghtOnly-normal.woff2"},
    {as = "font", type = "font/woff2", href = "/VictorMono-Medium.woff2"},
    {as = "style", href = "/main.css"}
]